# 端口号
server:
  port: 80
# 配置数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///o2ocrmams
    username: root
    password: 123456
  # redis连接信息
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
#    password:
    jedis:
      pool:
        max-active: 30  # 给定时间可以分配的最大连接数，使用负值表示没有限制
        max-idle: 10  # 最大空闲连接数
        min-idle: 1   # 最小空闲连接数
        max-wait: -1  # 连接池最大等待时间 -1表示没有限制
# 日志信息打印
logging:
  level:
    com:
      zfl19: debug
# 开启驼峰转换：
# 当出现手写sql语句之后，tk提供的自动驼峰转换就已经失效了，需要我们手动配置驼峰转换，是实体类中的属性字段能够与sql语句中的字段匹配
mybatis:
  configuration:
    map-underscore-to-camel-case: true